// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALOfynSQsyIDnDvbl5-IAXUOo7hYZIxCo',
    appId: '1:337426779657:web:73f7718bda85635684b2d8',
    messagingSenderId: '337426779657',
    projectId: 'my-first-project-802c7',
    authDomain: 'my-first-project-802c7.firebaseapp.com',
    storageBucket: 'my-first-project-802c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJfA1Rx-f-l0sGfi9gXQyIQV1kESyBgsw',
    appId: '1:337426779657:android:62597a23f42ead7c84b2d8',
    messagingSenderId: '337426779657',
    projectId: 'my-first-project-802c7',
    storageBucket: 'my-first-project-802c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr6msBhsDZUdyf3iBvpSQOb84nC5LAVQo',
    appId: '1:337426779657:ios:566c61cd855b0d0e84b2d8',
    messagingSenderId: '337426779657',
    projectId: 'my-first-project-802c7',
    storageBucket: 'my-first-project-802c7.appspot.com',
    iosClientId: '337426779657-15gubl2b0ju3aju4bsqru68rjsg0ervd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr6msBhsDZUdyf3iBvpSQOb84nC5LAVQo',
    appId: '1:337426779657:ios:566c61cd855b0d0e84b2d8',
    messagingSenderId: '337426779657',
    projectId: 'my-first-project-802c7',
    storageBucket: 'my-first-project-802c7.appspot.com',
    iosClientId: '337426779657-15gubl2b0ju3aju4bsqru68rjsg0ervd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
